### ISSUE TITLE
Wildly incorrect placement of the subscribe button and comments section, likely caused by a feature rollout.

### ISSUE THREAD

**Issue by IoIxD** [omnidevZero/YouTubeRedux#10]
![image](https://user-images.githubusercontent.com/30945097/149385058-ad8fb8d6-2905-4ac8-a05b-447cbbe88bd5.png)

When logged into my account, the new footer to videos still shows, but when logged into one of my alt accounts it's normal, which leads me to believe that Youtube is rolling out some weird minor change that breaks the extension.

I don't feel comfortable giving somebody access to my account but if you want to get in a Discord call and ask for the IDs of certain elements, my tag is @ioi_xd#­0­021

**Comment by IoIxD** [comment]
Yep.
The `ytd-watch-metadata` in `#primary-inner` now has tags `hidden` and `disable-upgrade`, and removing them forces you to see the layout that is being rolled out.

**Comment by omnidevZero** [comment]
Partially fixed in 2.13.2 (see [here](https://github.com/omnidevZero/YouTubeRedux/issues/31#issuecomment-1126816212)). Work on it will be continued after the change has been fully rolled out.

**Comment by KingGamingYT** [comment]
Adding some notes here post-patch:

5-16/17-22:
The partial fix layout is seemingly starting to break again, nothing major, however, it looks like the channel name and profile picture got divorced from the subscribe button.
![image](https://user-images.githubusercontent.com/45918062/168741805-5274db2f-b6b3-4a2e-a53a-94f8f8129477.png)
![image](https://user-images.githubusercontent.com/45918062/168741812-7ccc49df-5d0b-405d-82d6-2530164c185a.png)
