### ISSUE TITLE
Show github link in settings or add a way to visit the changelog page from settings

### ISSUE THREAD

**Issue by samiscool51** [omnidevZero/YouTubeRedux#104]
mainly to help users get to github so they can more easily report bugs, a simple button/link linking to the github with some text saying 'Github' or 'report a bug' would be better then nothing.

**Comment by omnidevZero** [comment]
The extension actually does contain a github link but it's displayed on the page that's shows on install and on updates (provided the user didn't disable showing changelogs). This page cannot be revisited on demand so I'll look into adding a way to do it.
