### ISSUE TITLE
Sorting a channels videos by date published is now gone. 

### ISSUE THREAD

**Issue by DeathWrench** [omnidevZero/YouTubeRedux#106]
You can no longer sort the videos on a channel by date, for some reason it got removed.

**Comment by KingGamingYT** [comment]
![image](https://user-images.githubusercontent.com/45918062/202918638-1d38418e-ccf1-4aa9-a94e-f90e08369296.png)
I am unable to replicate this issue. If you're talking about sort by oldest, youtube hid it with the new channel layouts, however, I'm sure it can be brought back at some time in the future.

**Comment by LautaroL20** [comment]
> KingGamingYT said: "I am unable to replicate this issue."

I think that he means shorting a channel's videos by oldest, which like you said, youtube has taken the stupid decision to hide it...

**Comment by KingGamingYT** [comment]
@LautaroL20 @DeathWrench After further research and consultation with people who know more then I do, it seems that sorting has been removed from YouTube’s primary API in its entirety, which would mean reimplementation would be tough if not impossible.
