### ISSUE TITLE
The buttons "cancel" and "comment" from the comment box are using a "bigger appearance"

### ISSUE THREAD

**Issue by LautaroL20** [omnidevZero/YouTubeRedux#107]
![The buttons cancel and comment from the comment box are using a bigger appearance](https://user-images.githubusercontent.com/12244376/203200807-4bd91b02-82cd-4eef-9132-1cd39faf7cb9.png)

Unfortunately, I was not able to find a screenshot of how the original size of these buttons looked in the past...

**Comment by omnidevZero** [comment]
Fixed in the upcoming update.

**Comment by LautaroL20** [comment]
Now fixed in Redux version 2.13.8.
