### ISSUE TITLE
Bug: studio.youtube.com is broken.

### ISSUE THREAD

**Issue by expertmanofficial** [omnidevZero/YouTubeRedux#114]
Without YT Redux enabled it works while having it enabled, it doesn't work :-(

Tested in LibreWolf 107.0, LM Cinnamon 20.3.

On my side issue exists :-1:

**Comment by omnidevZero** [comment]
In what way is it broken? Could you provide a screenshot of the issue please?

**Comment by expertmanofficial** [comment]
![image](https://user-images.githubusercontent.com/119038242/204874770-41cef8f5-6511-4e58-8c77-f8ea31194d57.png)
@omnidevZero no problem here you go.

**Comment by expertmanofficial** [comment]
just doesn't loads at all

**Comment by omnidevZero** [comment]
Thanks, I'll look into it.

**Comment by ArbestRi** [comment]
On Chrome, it works fine.

**Comment by expertmanofficial** [comment]
> On Chrome, it works fine.

in LibreWolf, in LM Cinnamon 20.3 it's not.
