### ISSUE TITLE
The "subscribed" button is big

### ISSUE THREAD

**Issue by gameshowrecaps** [omnidevZero/YouTubeRedux#117]
Just recently, when I am subscribed to a channel, the button appears to be so big.
![Screenshot 2022-12-07 193100](https://user-images.githubusercontent.com/57842610/206334024-813b9a1e-8a10-41d4-aef4-76ed811448a0.png)

**Comment by KingGamingYT** [comment]
YouTube has since rolled back this change.

**Comment by omnidevZero** [comment]
Although it was duplicated by #118 I'll close this one as the other issue gained more traction. Issue should be fixed in the upcoming update, thanks!
