### ISSUE TITLE
The subscribed button is now big and have a different symbol - It happens on a video page and in a channel's page.

### ISSUE THREAD

**Issue by LautaroL20** [omnidevZero/YouTubeRedux#118]
If I am not subscribed to a channel, the button will look fine, however if I am subscribed, the button will look as the image shown below:

![Image](https://user-images.githubusercontent.com/12244376/206333496-37501399-ce08-4e01-a8be-e562e7839249.png)

###  **This is how the subscribed button and it's counter looked before this happen:**

![Image](https://user-images.githubusercontent.com/12244376/206334936-732efa59-acf5-4032-a836-e15fd2b8d50c.png)

**Comment by Thespikedballofdoom** [comment]
Happening for me as well

**Comment by gameshowrecaps** [comment]
There's YouTube making changes to their UI, as usual.

**Comment by KingGamingYT** [comment]
![image](https://user-images.githubusercontent.com/45918062/206503876-a5e25689-72a5-46af-9339-3db1e5a019fc.png)
susan has made my sub button thin instead of thicc

**Comment by rg3017** [comment]
![subscribe](https://user-images.githubusercontent.com/25269939/206555844-61f44a17-ae8a-45e2-a2b4-b991f51d755a.jpg)
I'm getting the same thing, but the normal subscribe button is still there and the bell icon is the one getting the new design.

**Comment by KingGamingYT** [comment]
YouTube just rolled back the change, this is hilarious

**Comment by gameshowrecaps** [comment]
They brought it back.

**Comment by KingGamingYT** [comment]
goddamnit here we go again

**Comment by LautaroL20** [comment]
It started to happen again for me too.

**Comment by omnidevZero** [comment]
\***inhales**\*

**Comment by LautaroL20** [comment]
At this point, everything seems to indicate that Youtube will not revert this change, so @omnidevZero when you have the time, feel free to fix this.

**Comment by omnidevZero** [comment]
Already on it!

**Comment by LautaroL20** [comment]
Now fixed with the last update.

**Comment by KingGamingYT** [comment]
> Now fixed with the last update.

![image](https://user-images.githubusercontent.com/45918062/208229377-d55c6bcf-00c9-4e80-ba16-9f5ff300969b.png)
Duplicates Appeared!

**Comment by LautaroL20** [comment]
> KingGamingYT said: Duplicates Appeared! The leftmost one is the actual subscribe button, while the rightmost one is the notification bell posing as a subscribe button

For me, this is how the sub button looks in the last Redux update, vs how it looked before Youtube touched it:

![Before and now sub button](https://user-images.githubusercontent.com/12244376/208232493-21272f31-eb38-4f0e-aa63-e04390cb8d55.png)

**Also, do you think that the image below would be a good definitive version of the subscribe button and its bell? Look:**

![Ideally, this should be the definitive version of the subscribe button and its bell](https://user-images.githubusercontent.com/12244376/208232628-1e883fe0-8cbd-4675-9907-11f391bb4b4d.png)

**Comment by LautaroL20** [comment]
@KingGamingYT - So, how do you think that the sub button must look, did you ever see the last picture from my reply to your comment?

**Comment by KingGamingYT** [comment]
> @KingGamingYT - So, how do you think that the sub button must look, did you ever see the last picture from my reply to your comment?

The last image most closely resembles what it should.

**Comment by omnidevZero** [comment]
> > Now fixed with the last update.
> 
> ![image](https://user-images.githubusercontent.com/45918062/208229377-d55c6bcf-00c9-4e80-ba16-9f5ff300969b.png) Duplicates Appeared!
> 
> The leftmost one is the actual subscribe button, while the rightmost one is the notification bell posing as a subscribe button

What the hell! 😄 

> > KingGamingYT said: Duplicates Appeared! The leftmost one is the actual subscribe button, while the rightmost one is the notification bell posing as a subscribe button
> 
> For me, this is how the sub button looks in the last Redux update, vs how it looked before Youtube touched it:
> 
> ![Before and now sub button](https://user-images.githubusercontent.com/12244376/208232493-21272f31-eb38-4f0e-aa63-e04390cb8d55.png)
> 
> **Also, do you think that the image below would be a good definitive version of the subscribe button and its bell? Look:**
> 
> ![Ideally, this should be the definitive version of the subscribe button and its bell](https://user-images.githubusercontent.com/12244376/208232628-1e883fe0-8cbd-4675-9907-11f391bb4b4d.png)

Thanks for the comparison images, they help a ton. I'll try to improve it in the next update so it better matches the version before.

**Comment by KingGamingYT** [comment]
> > Now fixed with the last update.
> 
> ![image](https://user-images.githubusercontent.com/45918062/208229377-d55c6bcf-00c9-4e80-ba16-9f5ff300969b.png) Duplicates Appeared!
> 
> The leftmost one is the actual subscribe button, while the rightmost one is the notification bell posing as a subscribe button

I (kinda) fixed it by just adding a really simple piece of css to hide the subscribe button + bell combo, I'm left with only the subscribe button now, but I never change the bell settings anyway
![image](https://user-images.githubusercontent.com/45918062/208839877-ab35ccdc-5bc3-4e89-9d8c-1f41b45a0b77.png)
