### ISSUE TITLE
Watch page loads scrolled down a bit every time

### ISSUE THREAD

**Issue by toydotgame** [omnidevZero/YouTubeRedux#12]
See below image:
![image](https://user-images.githubusercontent.com/64190512/152494996-b1baf410-dc0c-4490-977b-d41b4f451454.png)
You can see the top of the video is partially obscured by the header:
![image](https://user-images.githubusercontent.com/64190512/152495052-4f515969-66c3-45f3-b4e9-0872bfa07a70.png)
So every time I have to scroll up to fix it.
![image](https://user-images.githubusercontent.com/64190512/152495183-7f0b555a-92f7-44a6-8e99-d5954a51ee83.png)

**Addon Version:** 2.11.8
**Browser (Firefox) Version:** 90.0.2
**OS:** Arch Linux 5.16.4

**Comment by omnidevZero** [comment]
Hey, I couldn't reproduce it. Check if there are any specific settings that might impact it.

**Comment by toydotgame** [comment]
I toggled _every single setting_. There's no difference, sorry.

**Comment by toydotgame** [comment]
If it's of any help, the page only scrolls down after the player loads. When the player is unloaded (just a black screen on the page), it's located below the navbar at its normal height, and the page scrolls only after a picture is loaded and displays.

**Comment by omnidevZero** [comment]
If the issue still occurs feel free to resubmit it.

**Comment by toydotgame** [comment]
Turns out it's the fault of the [YouTube High Definition](https://addons.mozilla.org/en-US/firefox/addon/youtube-high-definition/) addon (I was tipped off by [this](https://www.reddit.com/r/firefox/comments/lgkpr9/firefox_keeps_starting_youtube_video_pages/) Reddit thread), and not Redux. It just seemed to only start once I started using this addon. I've swapped it out for [Enhancer for YouTube](https://addons.mozilla.org/en-US/firefox/addon/enhancer-for-youtube/) for now as that has an option to override the quality for the player.

This issue is definitely resolved now, just posting this for those who might have the same issue on Google.
