### ISSUE TITLE
Gray "HD" in resolution list

### ISSUE THREAD

**Issue by lynrayy** [omnidevZero/YouTubeRedux#123]
Please make it red again in resolution list. Youtube again updating something, what no one asked
![image](https://user-images.githubusercontent.com/59417884/207561204-9fc1935f-66fa-414b-88fa-14704e53ee1d.png)

**Comment by TorutheRedFox** [comment]
thinking about it, getting rid of the colors on a lot of things is probably a way of making the site accessible to colorblind people from the get-go

but then again they could just make the design less flat and add some shadows to make certain elements pop

**Comment by lynrayy** [comment]
Why should healthy people suffer because of color blind people, huh? I see this problem in games too. And the same with sound - fewer and fewer games make sound a part of the gameplay. For example, in FNAF it was you had to listen from where and what sound comes from

**Comment by omnidevZero** [comment]
Will be fixed in the next update, thanks!
