### ISSUE TITLE
Rating bar on video page doesn't show dislikes portion

### ISSUE THREAD

**Issue by RenegadeScooter** [omnidevZero/YouTubeRedux#125]
![Screenshot 2022-12-16 154507](https://user-images.githubusercontent.com/69838290/208209032-f8c0dd76-c888-4221-a7a5-d5aef043a2dc.jpg)
Even when a video has dislikes **and** I set Thumbnail Rating Bar for YouTube to exponentially scale rating bars including bars added to video pages by Return YouTube Dislike, the rating bar shows all green when there should also be a portion of red in the bar.

BTW, if it helps, here's all the YouTube extensions I have installed:
![Screenshot 2022-12-16 154923](https://user-images.githubusercontent.com/69838290/208209342-9f9512d4-2dd4-4239-922c-7b0bb0004659.jpg)
...as well as my settings for YouTube Redux:
![Screenshot 2022-12-16 155630](https://user-images.githubusercontent.com/69838290/208210356-42866797-8443-4473-8c61-bd02a5f274fb.jpg)
![Screenshot 2022-12-16 155856](https://user-images.githubusercontent.com/69838290/208210398-48665141-5db4-45b8-ba3c-da15da67ccd5.jpg)
...Return YouTube Dislike:
![Screenshot 2022-12-16 160213](https://user-images.githubusercontent.com/69838290/208210631-96c407f8-2873-4bfe-a0a0-e183283e31d1.jpg)
...and Thumbnail Rating Bar for YouTube:
![Screenshot 2022-12-16 160347](https://user-images.githubusercontent.com/69838290/208210709-a6563738-dac3-4d34-adc3-5978fb14d80c.jpg)

Also, I am using LibreWolf (Firefox fork) version 108.0-1.

**Comment by omnidevZero** [comment]
Appreciate all the settings screenshots! Looks like Return YouTube Dislike doesn't like the rearranged video page layout so it doesn't report all the data required for Redux to update the bar. I'll look into it!

**Comment by RenegadeScooter** [comment]
Any updates on this issue?

**Comment by RenegadeScooter** [comment]
Any updates on this yet?
