### ISSUE TITLE
[Feature Request] Add an Option to Make the Recommended Sidebar small again

### ISSUE THREAD

**Issue by KingGamingYT** [omnidevZero/YouTubeRedux#13]
There wasn't a feature request tag, nor do I know if this is the right place for this, but I wanted to request that there be an option added, if possible, to bring back the smaller recommended bar next to videos that was around in 2015-2016. It had smaller thumbnails and a wider space for text, as well as unshortened view counts which benefitted from the wider space. I've attached an image (no actual thumbnails because it's from the wayback machine). 
![image](https://user-images.githubusercontent.com/45918062/152657169-fdb0ac02-b06e-466f-afab-983f4ec42a09.png)

**Comment by omnidevZero** [comment]
I can't restore the view count here as it's not stored within the page anymore but I'll look into adding some alternative look for the recommended/related section.
