### ISSUE TITLE
Chrome 68.0

### ISSUE THREAD

**Issue by lynrayy** [omnidevZero/YouTubeRedux#133]
Extension not working on chrome 68.0

**Comment by lynrayy** [comment]
![image](https://user-images.githubusercontent.com/59417884/211425760-50f28508-35e6-4c2c-9a8d-4301dd93432c.png)

**Comment by lynrayy** [comment]
It says "not supported"

**Comment by KingGamingYT** [comment]
> It says "not supported"

The extension recently got updated to Manifest V3 to comply with Google's new policies, since Chrome 68 is from 2018 (and some websites don't even support it anymore), it does not support Manifest V3. You'll have to manually acquire an older version of the extension from this repository which might work.

**Comment by ArbestRi** [comment]
@lynrayy Or download the latest version of Chrome. I'm pretty sure that's it's still on 68 because of the new Material Design 2.0 UI in 69

**Comment by lynrayy** [comment]
I don't want new UI. That's why i have chrome 68.
And plus in 68 i can mute tab just clicking on sound icon

**Comment by lynrayy** [comment]
Also i don't know how can i download old chrome and don't get autoupdate on it. I just randomly downloaded portable chrome and it appears 68.

**Comment by ArbestRi** [comment]
Also in Chrome 69 and 70 I believe there was an option to revert the UI to the older one

**Comment by lynrayy** [comment]
Ok, how can i download chrome 70 without auto-updating function? Preferably a portable version

**Comment by KingGamingYT** [comment]
Downloading a slightly newer version of chrome won't fix the root problem of not being able to install the extension. Besides, the experiment only existed until chrome 72 I believe when they removed it. If you're going to have this discussion, have it elsewhere so as not to clog up the thread with irrelevant info.

**Comment by ArbestRi** [comment]
I know that version 69 or 70 only support Manifest V2
