### ISSUE TITLE
Two scrollbars on video page

### ISSUE THREAD

**Issue by InsaneGal** [omnidevZero/YouTubeRedux#136]
I don't know if anyone else has posted about this issue, but since the last update the video pages has 2 scrollbars next to each other-- 1 being Chrome's default scrollbar and the 2nd being implemented through YouTube Redux. I disabled YouTube Redux and the 2nd scrollbar went away.

EDIT: Ok, so I unchecked "disable infinite scrolling" and that fixed it.

EDIT 2: The issue re-appeared regardless whilst watching videos.

**Comment by Thespikedballofdoom** [comment]
My friends without having redux also encountered this I think

**Comment by salehmu** [comment]
Same issue here

**Comment by Thespikedballofdoom** [comment]
This is getting really annoying, it seems to happen if the video is 16:9 or anything like that.
