### ISSUE TITLE
[Request] 'shorts' video type deflector

### ISSUE THREAD

**Issue by Thespikedballofdoom** [omnidevZero/YouTubeRedux#14]
Any video that has that shorts tag forcefully drags me to that horrible no-information tiktok nonsense ui. Can you add a toggle that moves shorts links back into normal watch?v= links?

**Comment by Franck-Nein** [comment]
@Thespikedballofdoom 
I made an Userscript to do that some time ago, so if you have Tampermonkey(or equivalent) you may use [YoutubeShortsRedirect.user.js](https://gist.github.com/Franck-Nein/4c10cced94638ff480e31256a9ebb860/raw/YoutubeShortsRedirect.user.js) for that until that gets implemented.

**Comment by Thespikedballofdoom** [comment]
Now that I think about it, it might be nice to nuke that label entirely and get the timecode back. It would help sift through memes easier. Can that be done?

**Comment by omnidevZero** [comment]
Almost a whole month later but the option to redirect has been added. New version will be available very soon.

> nuke that label entirely and get the timecode back

I'm not sure what you mean by that. Feel free to submit another issue regarding that. Thanks @Franck-Nein for a quick save with the userscript.
