### ISSUE TITLE
Video Preview in homepage doesn't work after enabling "homepage layout fix"

### ISSUE THREAD

**Issue by Soularstaryu** [omnidevZero/YouTubeRedux#146]
in homepage, when hovering mouse on video thumbnail it plays a sample from the video as a preview, after enabling the "hompage layout fix" it breaks and no longer works.

**Comment by DrLous** [comment]
Same here, when open subscriptions page and click on YT logo to switch home page. 
With home page fix layout => page without thumbnails (but I can click on, and video loading)
but if I reload => no problem.

Version 3.1.2 

Br.
