### ISSUE TITLE
YouTube script that reverts the new UI changes

### ISSUE THREAD

**Issue by Techfromthepast123** [omnidevZero/YouTubeRedux#149]
There is a script that reverts the rounded buttons and brings back the old filters button aswell has the old dark & light mode.
This should be included into Youtube redux because it fixes alot of stuff:
https://github.com/aubymori/YouTubePatchCollection/issues

**Comment by KingGamingYT** [comment]
YT Patch Collection has been slowly crumbling over time, aubrey doesn't maintain it anymore.

**Comment by KingGamingYT** [comment]
> Oh too bad because it brings back the grey dark mode. Maybe omnidevzero should add an option to bri'g back the old grey darkmode.

Right, I forget sometimes that redux hasn't actually fixed that. I have a userstyle that helps revert some elements of darker dark and other things like fonts.
[restore.txt](https://github.com/omnidevZero/YouTubeRedux/files/10923499/restore.txt)

**Comment by TorutheRedFox** [comment]
i honestly prefer the slightly lighter dark theme lol
