### ISSUE TITLE
ecks dee

### ISSUE THREAD

**Issue by StickmanIsHere** [omnidevZero/YouTubeRedux#152]
![image](https://user-images.githubusercontent.com/127046802/223710993-6c2f30d6-58fe-4cfa-b1fa-5c701ac35205.png)

**Comment by KingGamingYT** [comment]
and how is this a redux issue exactly

**Comment by Techfromthepast123** [comment]
Wait I see the issue here,it's not the bar that he is talking about but the dislikes text color when the button is clicked.
When you click the like or dislike button,the text should colorize with it aswell,but in this screenshot,it stays white,I thinkg it is a youtube redux issue.
