### ISSUE TITLE
Is the developer of this extension even updating it anymore ?

### ISSUE THREAD

**Issue by Techfromthepast123** [omnidevZero/YouTubeRedux#153]
The developer of YouTube Redux hasn't updated his extension in 2 months I think now and he didn't respond to any of the latest issues on this github page.
I am wondering if he still updates or cares about this extension.

**Comment by KingGamingYT** [comment]
He disappeared for like 3 months at the beginning of 2022 so I have feeling he's just busy with personal stuff.

**Comment by StickmanOnGitHub** [comment]
No idea.

**Comment by omnidevZero** [comment]
I'm also hoping for the developer to finally stop slacking off and start working on persisting issues! *wink* *wink*

**Comment by Techfromthepast123** [comment]
Wait arent you the developper of YouTube Redux ?
OmnidevZero

**Comment by omnidevZero** [comment]
Hence the winking part 😜

**Comment by Thespikedballofdoom** [comment]
Yaoooo

**Comment by ImprovedTube** [comment]
you 
# 2025
## 2025
### 2025
