### ISSUE TITLE
Like/Dislike Bar ratio broken

### ISSUE THREAD

**Issue by NickieForRealz** [omnidevZero/YouTubeRedux#156]
currently installed "Return youtube dislikes" and it clearly shows the like dislike ratio on a video (the bar either above or below the like and dislike button)

![(30) YouTube Rewind 2018_ Everyone Controls Rewind _ #YouTubeRewind - YouTube and 9 more pages - Personal - Microsoft​ Edge 4_30_2023 6_09_06 PM](https://user-images.githubusercontent.com/104857543/235380397-1b1ecc61-eda6-4cb6-a71d-9d144d8aa2b5.png)

however the youtube redux version dosent show that

![(30) YouTube Rewind 2018_ Everyone Controls Rewind _ #YouTubeRewind - YouTube and 9 more pages - Personal - Microsoft​ Edge 4_30_2023 6_09_41 PM](https://user-images.githubusercontent.com/104857543/235380448-fd75eab9-29dc-4f9e-a814-9a6a1984532d.png)

**Comment by omnidevZero** [comment]
Fixed but not fixed. Now it's broken when not using precise values. Will be fixed soon!
