### ISSUE TITLE
[YT Redux V. 3.1.0] Darker red color not working on the Subscribe button.

### ISSUE THREAD

**Issue by LautaroL20** [omnidevZero/YouTubeRedux#159]
Darker red is only working in the YT left menu, but not in the subscribe button:

![Darker red color not working on the subscribe button](https://user-images.githubusercontent.com/12244376/236660261-77816ba4-c462-4e28-9833-23618b3724a9.png)

**Comment by omnidevZero** [comment]
Will be fixed in the upcoming update. While I was at it I also added the darker color to active tab underline which was always using the bright one.

**Comment by LautaroL20** [comment]
This is now fixed.
