### ISSUE TITLE
[request] autoplay perma-off-setter

### ISSUE THREAD

**Issue by Thespikedballofdoom** [omnidevZero/YouTubeRedux#16]
Youtube made a new bug that turns it on constantly. I have a feeling this bug is gonna come back even after they fix it.

**Comment by mutageneral** [comment]
is this a bug with this add-on or a bug with YouTube? ider way I would like this

**Comment by Thespikedballofdoom** [comment]
It's a bug with youtube itself, you have to clear your cookies on youtube to fix it, it hasn't happened for me again after I did that. shouldve closed this earlier
