### ISSUE TITLE
[YT Redux V. 3.1.0] The "Oldest" button is having some issues.

### ISSUE THREAD

**Issue by LautaroL20** [omnidevZero/YouTubeRedux#160]
* **Sometimes the Oldest button does not appear until the page is refreshed.**
* **When the Oldest button is clicked, this button can disappear if you then switch to the "Latest" or "Popular" button.**

### **Here is a video showing how to replicate the mentioned issues: https://www.youtube.com/watch?v=HSbZzkWuidw**

**Comment by omnidevZero** [comment]
Thanks for that! YouTube really doesn't like having new elements attached to it and it's often removing them on page navigation or other actions so I ended up adding some ugly delays after which the Oldest button is added to the page and it worked fine on my end but looks like it needs some improvements. Will do!

**Comment by omnidevZero** [comment]
Improvement incoming in 3.1.1!

**Comment by LautaroL20** [comment]
Nice :)

**Comment by LautaroL20** [comment]
One of the two bugs mentioned is fixed, but the bug of the Oldest button not appearing until the page is refreshed is still happening, and now it seems to happen all the time. See issue: #163

**Comment by LautaroL20** [comment]
Closing in favor of: #163
