### ISSUE TITLE
Buggy buttons on watch page

### ISSUE THREAD

**Issue by GemplelyTivadar** [omnidevZero/YouTubeRedux#163]
When I press the share button it gives the url of the previous video I watched instead of the one I'm currently watching.
The same thing happens with the save button, instead of adding the video I'm currently watching to a playlist, it's adding the video I watched before this one.
![Untitled](https://user-images.githubusercontent.com/95102462/236706531-e92df073-efca-4bec-afad-42a6863fef23.png)

Sometimes the share button disappears.
![Screenshot from 2023-05-08 00-05-27](https://user-images.githubusercontent.com/95102462/236706616-414cc42b-bc75-4dc0-9199-adc20188aea5.png)

Sometimes only the ... button is visible
![Screenshot from 2023-05-08 00-00-17](https://user-images.githubusercontent.com/95102462/236706699-5d1d8bde-2d15-42b0-a025-526c16ad87ab.png)

Sometimes the share button has the save icon, and the save button has the default YouTube icon instead of the custom icon from Redux.
![Screenshot from 2023-05-08 00-42-40](https://user-images.githubusercontent.com/95102462/236706801-36a2c838-3587-40b3-b320-f0a621c48280.png)

**Comment by Thespikedballofdoom** [comment]
So that's why my playlists kept getting weird wrong videos

**Comment by omnidevZero** [comment]
Fix incoming! There was a conflict with Return YouTube Dislike that caused this issue.
