### ISSUE TITLE
The page does not switch when you click the video.

### ISSUE THREAD

**Issue by Aoi-021** [omnidevZero/YouTubeRedux#165]
As the title,
the page does not switch when you click the video, but the music starts to play,
YouTube Redux uses a full default setting, maybe is not a bug, can someone help me with this?
Please refer to the video for symptoms: https://gofile.io/d/2xAyir

**Comment by omnidevZero** [comment]
Quite a critical issue, however I'm not able to reproduce it. If anybody else has more info about it I'd appreciate it. It's possible that it has to do with some YT changes that aren't rolled out to most users yet.
