### ISSUE TITLE
Sign in button in YT Redux is not accurate to the one used in the old YouTube layout.

### ISSUE THREAD

**Issue by Techfromthepast123** [omnidevZero/YouTubeRedux#166]
YouTube Redux:

![Capture d'écran 2023-05-08 124409](https://user-images.githubusercontent.com/112059671/236815764-5c774b6e-c59e-4ca2-b560-e787b8d003dd.png)

Old YouTube layout:

![Capture d'écran 2023-05-08 124333](https://user-images.githubusercontent.com/112059671/236815809-4bff5002-1cab-4cd8-8524-383b43090f31.png)

**Comment by omnidevZero** [comment]
Fix incoming!
