### ISSUE TITLE
Red Text on sidebar should be capitalized

### ISSUE THREAD

**Issue by Techfromthepast123** [omnidevZero/YouTubeRedux#167]
YouTube Redux:

![Capture d'écran 2023-05-08 124827](https://user-images.githubusercontent.com/112059671/236816391-3b623c45-ce8c-44f4-80ca-dc30a9dd6f59.png)

Old YouTube Layout:
![Capture d'écran 2023-05-08 124850](https://user-images.githubusercontent.com/112059671/236816429-9e1b8cc5-46f7-41c3-875e-921762e05059.png)

**Comment by omnidevZero** [comment]
Will be fixed in the upcoming update, thanks!
