### ISSUE TITLE
Remove Sort By Oldest Mod

### ISSUE THREAD

**Issue by KingGamingYT** [omnidevZero/YouTubeRedux#189]
With YouTube bringing back sort by oldest proper, I recommend the custom implementation redux has to be given a toggle to disable it or for it to be removed outright.

**Comment by LautaroL20** [comment]
On my side, YT did not bring it back, so i am not sure if they will going to finally implement it.

**Comment by KingGamingYT** [comment]
> On my side, YT did not bring it back, so i am not sure if they will going to finally implement it.

It's a gradual rollout, I don't have it yet either.

**Comment by Thespikedballofdoom** [comment]
i managed to get it

**Comment by LautaroL20** [comment]
I can now confirm that on my side, Youtube has finally put again the "short by oldest" feature. So, it now seems that YT have implemented this feature for most or even all of us.

**Comment by Thespikedballofdoom** [comment]
Maybe a filter will work for now
```#redux-sort-chip{
    display:none !important
}```

**Comment by KingGamingYT** [comment]
> There's already a toggle for it under **Misc** settings. ![3VDMW1ojmW](https://user-images.githubusercontent.com/96963229/248515893-f75653aa-dfbb-4da2-8f15-a909de5868b4.png)

I must have missed this. Thank you. (I have also since regained proper oldest sort)

**Comment by omnidevZero** [comment]
Took me over a year but I just got rid of it 😄
