### ISSUE TITLE
[bug] front page doesnt load more videos until you scroll to the very bottom

### ISSUE THREAD

**Issue by nanopone** [omnidevZero/YouTubeRedux#19]
front page doesnt load more videos until you scroll to the very bottom which causes the page to anchor to the bottom and keep loading more and more videos scrolling you further and further down

https://user-images.githubusercontent.com/49787675/157930225-e013b983-0d3d-47c6-b557-91c97b9d92df.mp4

**Comment by omnidevZero** [comment]
Super old issue but if it still occurs feel free to resubmit it.
