### ISSUE TITLE
Redux is now slowing down Firefox

### ISSUE THREAD

**Issue by gameshowrecaps** [omnidevZero/YouTubeRedux#191]
On the video page, things take a very long time to load and uses up a LOT of memory.

**Comment by Thespikedballofdoom** [comment]
cant confirm

**Comment by gameshowrecaps** [comment]
Tried installing and uninstalling and it still uses up memory and takes a long time to load. (Firefox only)

**Comment by SeberHusky** [comment]
Also having the same issue. Typing comments is very sluggish, and the 3-dot menu next to each video on the subscription page takes about 10 seconds to load in to be clickable. Videos sometimes stutter.  It does not happen with Redux disabled. This problem started right after the new homepage layout dropped and has persisted for the past couple months.

**Comment by gameshowrecaps** [comment]
It's most definitely because of a new YT change messing things up.
