### ISSUE TITLE
safari port/userscript

### ISSUE THREAD

**Issue by peepee** [omnidevZero/YouTubeRedux#2]
would it be possible to port this to safari or make it a standalone userscript?

**Comment by Franck-Nein** [comment]
Tried to do an automatic conversion, it works on my vm(MacOS 11.5.2 Safari 14.1.2).
https://github.com/Franck-Nein/YouTubeRedux/releases/download/Test/YouTube.Redux.app.zip

**Comment by peepee** [comment]
> Tried to do an automatic conversion, it works on my vm(MacOS 11.5.2 Safari 14.1.2) but I can't guarantee anything.
> https://github.com/Franck-Nein/YouTubeRedux/releases/download/Test/YouTube.Redux.app.zip

i'm on macos 10.15.7 with safari 15.1 and it doesn't seem to work :(
![image](https://user-images.githubusercontent.com/49787675/142937569-f69e8563-801b-40e1-ab28-7ef9ed5c56ce.png)

**Comment by Franck-Nein** [comment]
> > Tried to do an automatic conversion, it works on my vm(MacOS 11.5.2 Safari 14.1.2) but I can't guarantee anything.
> > https://github.com/Franck-Nein/YouTubeRedux/releases/download/Test/YouTube.Redux.app.zip
> 
> i'm on macos 10.15.7 with safari 15.1 and it doesn't seem to work :( 
You need to allow Unsigned Extensions
Safari > Preferences > Advanced tab > Show Develop menu in menu bar
Develop > Allow Unsigned Extensions
24 second guide just in case:
https://youtu.be/VOc_7iRy2wU

**Comment by peepee** [comment]
allowing unsigned extensions worked! thank you!
