### ISSUE TITLE
Creative Commons licensing information no longer appears when extension is enabled

### ISSUE THREAD

**Issue by ixfd64** [omnidevZero/YouTubeRedux#21]
On videos with a Creative Commons license, the licensing information no longer appears when the extension is active. This issue seems to have only appeared recently.

**To reproduce**

1. Go to any video with a Creative Commons license. Example: https://youtube.com/watch?v=YD6pdDWl4ts

**Expected results:**

The text "Creative Commons Attribution license (reuse allowed)" should appear.

![youtube-cc1](https://user-images.githubusercontent.com/1526759/159106257-82c7ca9c-818e-497d-858e-2adb6503dd95.png)

**Actual results:**

No licensing information is visible.

![youtube-cc2](https://user-images.githubusercontent.com/1526759/159106308-c96403d4-2208-43b9-b9e4-b3b52f8993b7.png)

I am using Chrome on Windows 10 Home.

**Comment by omnidevZero** [comment]
Video licensing information is hidden by default as to match the old layout. However, this part specifically can be restored as it's a separate setting: 
![image](https://user-images.githubusercontent.com/74119439/159133354-d870d4e4-9872-4567-98d1-489c30782793.png)
uncheck "Video licensing" within "Hide features" section so it won't be hidden.

**Comment by ixfd64** [comment]
This resolves the issue. Thanks!
