### ISSUE TITLE
(Bugs from the new update) Like bar detaches and floats after reccomendations are clicked 

### ISSUE THREAD

**Issue by Thespikedballofdoom** [omnidevZero/YouTubeRedux#216]
![cap_23-10-2023_06 20 09PM_xx](https://github.com/omnidevZero/YouTubeRedux/assets/43627353/3e0f9623-11e8-4cb3-9b16-be2d2ff6a64f)

**Comment by gameshowrecaps** [comment]
Still in 3.3.0, but it doesn't really bother me.
