### ISSUE TITLE
Issues with description: see attached image

### ISSUE THREAD

**Issue by dankxen0n** [omnidevZero/YouTubeRedux#225]
![image](https://github.com/omnidevZero/YouTubeRedux/assets/71655697/15651af5-8126-4867-b947-bab19915a3c8)

**Comment by riderofblack22** [comment]
Same issue here. Just started today

**Comment by DrBrad22** [comment]
same. :/

**Comment by gameshowrecaps** [comment]
I haven't noticed this issue yet, likely YouTube pushing something with A/B testing.

**Comment by riderofblack22** [comment]
Can confirm it's a testing feature. I tried using my other account and it looks as it should. Hopefully this is resolved sooner rather than later

**Comment by gameshowrecaps** [comment]
Got it on my alt (which I do not use as much). YouTube's doing stuff as per usual.
