### ISSUE TITLE
Like and dislike buttons moved due to YouTube change

### ISSUE THREAD

**Issue by MarisaKirisame-ze** [omnidevZero/YouTubeRedux#228]
YouTube decided to change layouts again to make the site EVEN WORSE, now the like and dislike buttons are in the wrong place.

![image](https://github.com/omnidevZero/YouTubeRedux/assets/86389939/2198c6ff-cc24-4cd3-8cff-70257a5f94ca)

**Comment by riderofblack22** [comment]
fully out now, no longer a/b it seems

**Comment by MarisaKirisame-ze** [comment]
What do you mean?

**Comment by riderofblack22** [comment]
This was an issue like a week ago, but only for a few people, it looks like YouTube fully rolled it out now

**Comment by gameshowrecaps** [comment]
I don't have this change on my main still, thankfully. Must be very few people that didn't get this change.

**Comment by NotAViper** [comment]
Yup I have the same issue
