### ISSUE TITLE
Dislike button is moved and number of subs doesn't display correcty

### ISSUE THREAD

**Issue by Kameleone** [omnidevZero/YouTubeRedux#229]
Hi, I have YTRedux 3.3.0 on Firefox and despite update there is still bug with displaying dislikes number. Number is next to share button, not to dislike button. Another issue is that when I enabled setting "Trim subscribers count". Instead of showing only number of subscriptions it doesn't show anything at all.
![Screenshot 2023-12-01 234556](https://github.com/omnidevZero/YouTubeRedux/assets/127246999/16a185a9-5cd6-419e-9e67-3dc3a1bbfdf2)

**Comment by riderofblack22** [comment]
Download the new source code for Return Youtube Dislike on TamperMonkey and it'll be fixed (they are working on submitting the new version to extension stores)

**Comment by Kameleone** [comment]
@riderofblack22 thank you, it worked. but I'll leave issue open for now.
