### ISSUE TITLE
Ads appearing in the home page.

### ISSUE THREAD

**Issue by MrSkullium** [omnidevZero/YouTubeRedux#235]
I have ublock origin and all ads have been blocked except for the homepage for some reason. With it showing a sponsored video on the top of the homepage. I tried turning off youtube redux as well as using another addon that replaces the loadout, and no sponsored posts appear except for redux, which is consistent.
### **With redux**
![Screenshot (1982)](https://github.com/omnidevZero/YouTubeRedux/assets/66441517/a08675e1-9eb5-465a-9249-b0ad09aa250e)
### **Without redux**
![Screenshot (1983)](https://github.com/omnidevZero/YouTubeRedux/assets/66441517/07bd28b8-8ba6-4d08-a8b8-e4d5295eca05)
### **With another addon that replaces the layout (Customtube)**
![Screenshot (1984)](https://github.com/omnidevZero/YouTubeRedux/assets/66441517/2014799e-b329-4fec-8fea-83e8dac77a5c)

**Comment by omnidevZero** [comment]
The upcoming v3.4.1 should resolve it.
