### ISSUE TITLE
UI is breaking

### ISSUE THREAD

**Issue by dankxen0n** [omnidevZero/YouTubeRedux#247]
![image](https://github.com/omnidevZero/YouTubeRedux/assets/71655697/258d6b32-87dc-428b-85d4-432136eb5c6d)
rounded corners on banner, channel icon, and subscribe button

**Comment by mikeyiscool10** [comment]
its just because it hasnt been updated in a bit

**Comment by userunknown358** [comment]
YouTube Redux is not that accurate unfortunately. If you want the old YouTube Layout, consider switching to V3

**Comment by omnidevZero** [comment]
Been so long but believe it or not, it will be fixed in the next update!

**Comment by userunknown358** [comment]
> Been so long but believe it or not, it will be fixed in the next update!

Have you ever considered moving the about page back to where is was before mid-2023?

**Comment by omnidevZero** [comment]
> Have you ever considered moving the about page back to where is was before mid-2023?

Which change do you have in mind? Could you link some screenshot that describes it? If you mean moving it back to the bottom of the page then it's unlikely due to infinite scrolling .
