### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'getBoundingClientRect')     at main.js:237:101

### ISSUE THREAD

**Issue by cyan-2048** [omnidevZero/YouTubeRedux#25]
fix: `document.querySelector('#player-container-outer')?.getBoundingClientRect().x;`

**Comment by omnidevZero** [comment]
The entire small player/page resizing code is such a mess that I'm pretty afraid to touch it! Anyway this will be fixed shortly, thanks!

**Comment by omnidevZero** [comment]
Closing as it's been fixed for a while now.
