### ISSUE TITLE
View counters and upload dates from previous videos are still there when I watch a new video.

### ISSUE THREAD

**Issue by Jupiteron** [omnidevZero/YouTubeRedux#254]
![Screenshot 2024-08-09 003056](https://github.com/user-attachments/assets/26bd63c1-fdd2-451e-bc11-04a5b799fc56)
Everytime I click on a new video, the view counter and the upload date from the previous video is still there. This bug can only be fixed when I refresh the video page.

**Comment by userunknown358** [comment]
I think YouTube Redux is temporarily discontinued or something. The last update was around May 6th 2023

**Comment by Megalaoofania** [comment]
> I think YouTube Redux is temporarily discontinued or something. The last update was around May 6th 2023

No, this project is still active and is actively receiving updates, but this issue is still a problem.
![image](https://github.com/user-attachments/assets/8d15adec-fb77-4c43-a762-55e5a292e7ae)

**Comment by omnidevZero** [comment]
Does it happen everytime? I couldn't reproduce this issue. Could you see if there is any specific Redux setting that could be causing it?

**Comment by Megalaoofania** [comment]
> Does it happen everytime? I couldn't reproduce this issue. Could you see if there is any specific Redux setting that could be causing it?

It seems like the "Use alternative video page layout" (with or without the like/dislikes also rearranged) breaks it.

**Comment by omnidevZero** [comment]
Not really a fix but the setting that caused this issue was removed as it wasn't working properly anyway so this issue should no longer occur.
