### ISSUE TITLE
Title, comments and recommended does not load frequently and reloading causes cached metadata from previous videos to appear on new videos 

### ISSUE THREAD

**Issue by qfoxb** [omnidevZero/YouTubeRedux#255]
Content not loading
![image](https://github.com/user-attachments/assets/c730797f-1034-468e-8bb7-28866e174e51)
Metadata caching (verified that it is not any other extension causing this)
![image](https://github.com/user-attachments/assets/d4b72a2a-e979-49af-8362-3902fb2137b9)

**Comment by qfoxb** [comment]
After further testing it is being caused by "Annotations Restored for YouTube"

**Comment by qfoxb** [comment]
nevermind it is occuring without this now

**Comment by natewu** [comment]
Same issue here, in addition, comments are not loading either

**Comment by babzai** [comment]
same issue

**Comment by ZWho1963** [comment]
It's getting annoying to reload a page specifically to load its metadata. Hopefully this gets patched soon.

**Comment by omnidevZero** [comment]
It will! Got the fix ready, will be pushed alongside other fixes pretty soon!

**Comment by natewu** [comment]
> It's getting annoying to reload a page specifically to load its metadata. Hopefully this gets patched soon.

Agree, its quite annoying, every single video I click needs a refresh (it also does not autoplay if you refresh, you need to click the play button)

**Comment by natewu** [comment]
> It will! Got the fix ready, will be pushed alongside other fixes pretty soon!

new version that just got released fixed the issues :rocket:
