### ISSUE TITLE
Video data won't update

### ISSUE THREAD

**Issue by Saturn-sepehr** [omnidevZero/YouTubeRedux#256]
when clicking on a new video, the name of the uploader, view count and other information about the video won't get updated to the ones from the video that got clicked (same with the recommended sidebar)

**Comment by nanakisan** [comment]
Confirming this post. Was just about to make this report as well. Same exact issue as listed.

**Comment by jackhacksren** [comment]
the devs have fucking died we gotta fork the youtube redux and do our own work now this redux has over 100+ issues none of these r getting fixed soon

**Comment by Laenthor12** [comment]
Gotta abandon ship and take in the new UI I guess.

**Comment by omnidevZero** [comment]
> the devs have fucking died we gotta fork the youtube redux and do our own work now this redux has over 100+ issues none of these r getting fixed soon

Hold that thought for just a moment! Let me turn 165 issues into 164! 🤭

**Comment by nanakisan** [comment]
Whatever you did. It worked.

**Comment by Thespikedballofdoom** [comment]
AWESOME
