### ISSUE TITLE
YouTube watch page takes up all of CPU's resources

### ISSUE THREAD

**Issue by CobaltonGit** [omnidevZero/YouTubeRedux#257]
This is most likely a null pointer error, as the extension tries to load in resources that do not exist, therefore 100% CPU usage.

**Comment by omnidevZero** [comment]
On it!

**Comment by omnidevZero** [comment]
As a workaround, while waiting for the fix to go live, you can disable "Show precise values for likes/dislikes" setting which causes this issue.

**Comment by Thespikedballofdoom** [comment]
It's fixed!
