### ISSUE TITLE
YouTube has changed the Progress Bar to a red to Pink gradient for some users as an experiment. pls fix

### ISSUE THREAD

**Issue by mutageneral** [omnidevZero/YouTubeRedux#261]
Video about this: https://youtu.be/KJcLwknsyw0

My title bar is a red to pink gradient:
![image](https://github.com/user-attachments/assets/d2ea98fc-8e5c-43e0-9387-e8960856e349)
please add option to turn this off, thanks

here is more info:
![image](https://github.com/user-attachments/assets/f9c25f83-c52b-4958-94d0-015cacceb0eb)

**Comment by omnidevZero** [comment]
Will be fixed in the next update 👍

**Comment by VerMishelb** [comment]
Can the colours of these be exposed in control panel or are manual code edits the only way to do so? I was using the following script lately to get rid of pinkish colours and ended up with colours which resemble the old player:
![изображение](https://github.com/user-attachments/assets/604dcb76-6892-4ecc-a7ba-98982d840292)
But after the update YTR seems to take priority over a tampermonkey script.
```css
const colorHex = "#cc181e";
const colorHexScrubber = "#ececec";
...
const seekBarElements = document.getElementsByClassName("ytp-play-progress ytp-swatch-background-color");
const thumbnailElements = document.getElementsByClassName("style-scope ytd-thumbnail-overlay-resume-playback-renderer");
const scrubberButtonElements = document.getElementsByClassName("ytp-scrubber-button ytp-swatch-background-color");
const navbarElements = document.getElementsByClassName("yt-page-navigation-progress");

for (let i = 0; i < seekBarElements.length; i++) {
    seekBarElements[i].style.background = colorHex;
}
for (let i = 0; i < thumbnailElements.length; i++) {
    thumbnailElements[i].style.background = colorHex;
}
for (let i = 0; i < scrubberButtonElements.length; i++) {
    scrubberButtonElements[i].style.background = colorHexScrubber;
}
for (let i = 0; i < navbarElements.length; i++) {
    navbarElements[i].style.background = colorHex;
}
```

**Comment by omnidevZero** [comment]
YTR changes the progress bar colors via the following code:
```
.ytp-swatch-background-color {
    background-color: #f00 !important;
    background-image: none !important;
}
```
So you'd have to override the !important property for these elements in your script which can be done via JS (e.g. with element.style.setProperty()) or via CSS by providing more specific selectors than in the code above.
