### ISSUE TITLE
YouTube "Live Chat Replay" Prompt Panel Inside Description

### ISSUE THREAD

**Issue by Narixv** [omnidevZero/YouTubeRedux#263]
Recently it seems YouTube has been experimenting with placing a "promt panel" inside of the description to open the live chat replay.
In a future update can this removed?
(see attached)
Thank you for your hard work!

![YT_10 31 24_A](https://github.com/user-attachments/assets/871dd391-9463-48af-b14a-c1e903059b81)
![YT_10 31 24_B](https://github.com/user-attachments/assets/cd4f4cb7-e876-4a8e-ad3c-2048846fea10)

**Comment by omnidevZero** [comment]
The upcoming update will add an option to hide it which will be enabled by default.
