### ISSUE TITLE
Copy and pasting link and entering it in browser freezes YouTube

### ISSUE THREAD

**Issue by gameshowrecaps** [omnidevZero/YouTubeRedux#264]
This seems to happen 50% of the time whenever I paste a YouTube link in my browser and press enter (aka finding a link to a video quickly rather than searching for it)

Refreshing the page fixes this.
![image](https://github.com/user-attachments/assets/177d4b25-6929-4c1b-89e9-c60d4bd418f3)

**Comment by omnidevZero** [comment]
I'm having trouble reproducing it. Try and see if the extension throws some errors in the console when that happens (F12 > Console, originating from main.js file).

**Comment by gameshowrecaps** [comment]
May be a possibility YouTube may be A/B testing something in that case. I'll come back to this if I can get this problem to happen with inspect on.

**Comment by gameshowrecaps** [comment]
It has been a week and I have not had this problem happen at all with inspect on. Will reopen if this problem occurs again.

**Comment by gameshowrecaps** [comment]
The issue has finally happened. Have used inspect to find the error:
![Screenshot 2024-11-30 012327](https://github.com/user-attachments/assets/bf96839e-40c9-4e56-bbbd-0f87cc188b86)

**Comment by gameshowrecaps** [comment]
Keeping this closed, as it seems like it's a Firefox issue, not a Redux issue. Also saw this occur without Redux occurring.
