### ISSUE TITLE
Changelog appeared but then was replaced with Youtube

### ISSUE THREAD

**Issue by Nicholas-Steel** [omnidevZero/YouTubeRedux#265]
> changelog will now only be displayed when visiting YouTube instead of being triggered globally in the browser

The changelog appeared when I opened Youtube in another tab in the background (middle-clicked a bookmark) but then when I changed to the tab it was replaced with the Youtube page. Or... something like that, wish I was recording video when it happened.

Maybe what happened was I opened 2 Youtube tabs and changing between them cleared the changelog from the first tab.

Latest stable Firefox for Windows 10, 132.1

**Comment by omnidevZero** [comment]
When the changelog tab is created it also becomes the active tab. Perhaps you navigated to YouTube at the same time as the changelog page opened? Let's see if anyone else has the same issue 😉
