### ISSUE TITLE
True full screen mode still scrolls

### ISSUE THREAD

**Issue by natewu** [omnidevZero/YouTubeRedux#269]
With true full screen mode enabled, the video in full screen if you click the part under the video time selector or scroll it will still scroll the screen. 

Unable to return to the full screen by scrolling up, have to exit and re-enter full screen to see the top of the video again

**Comment by omnidevZero** [comment]
I just pushed an update that disables the scrolling behavior when clicking below the progress bar while in true fullscreen mode.
