### ISSUE TITLE
Pale Moon Browser Compatibily?

### ISSUE THREAD

**Issue by JeremyLyokoPPG2020** [omnidevZero/YouTubeRedux#29]
i tired install add-on YouTubeRedux xpi file but could not installed because Pale Moon
![image](https://user-images.githubusercontent.com/30205044/167600994-f2b5f0a7-bd5e-4601-ab9a-893219e5c7e7.png)

**Comment by KingGamingYT** [comment]
This seems to be moreso a Pale Moon issue rather than a Redux issue. After doing some research, Pale Moon only works with plugins made for it, none from the Mozilla addons site.

**Comment by omnidevZero** [comment]
Well, the answer is in the attached screenshot - Pale Moon does not support WebExtensions. That includes YouTube Redux. You might give [Moon tester tool](https://github.com/JustOff/moon-tester-tool) a try and see if it installs the extension successfully.
