### ISSUE TITLE
Number of videos per row not working properly.

### ISSUE THREAD

**Issue by Franck-Nein** [omnidevZero/YouTubeRedux#3]
Setting 'Number of videos per row (main page)' to anything other than 4 only results on the scale changing, but doesn't change the amount of videos per row (it does randomly work sometimes), issue happens in both Firefox and Chrome(Chromium)
Screenshots(Blurred for reasons):
Set to 6 
![Screenshot_2021-11-26 YouTube](https://user-images.githubusercontent.com/35365671/143563661-d5900ec5-bfb6-477d-8f6f-e07128c210ae.png)
Set to 2
![Screenshot_2021-11-26 YouTubea](https://user-images.githubusercontent.com/35365671/143563691-d02b25b9-5664-4910-869b-96c60b737f74.png)
Rest of the settings
![image](https://user-images.githubusercontent.com/35365671/143564033-d15c01af-100d-40d6-b8e4-e4c88a75c1d0.png)
Video to better illustrate:

https://user-images.githubusercontent.com/35365671/143565838-1587401a-acdb-4b08-a5d2-f377cfc6c3d7.mp4

**Comment by LaeMat** [comment]
Same issue. Even on 4, i'll still get random gaps in the homepage at the top right cornet.
![image](https://user-images.githubusercontent.com/87903194/143627812-a522ea75-7871-4e93-a1c6-23e020ae5fe9.png)

**Comment by Franck-Nein** [comment]
> Same issue. Even on 4, i'll still get random gaps in the homepage at the top right corner. 

That gap happens when AdBlock(or equivalent) hides one of those ads that are disguised as a video, disabling cosmetic filters should fix it, but you will see the ad.
Cosmetic filter on:
![mpv-shot0002](https://user-images.githubusercontent.com/35365671/143691470-006f1d05-6996-4091-bb51-8f1596e996fa.png)

Cosmetic filter off:

![mpv-shot0001](https://user-images.githubusercontent.com/35365671/143691475-58a798a4-ec70-4873-9798-329727f916fc.png)

**Comment by omnidevZero** [comment]
I'm aware of this issue but thanks for reporting it regardless. I haven't worked on it because YouTube kept going back and forth with their layout breaking changes. Looks like it's going to stick though so I'll try to have it fixed soon.

**Comment by omnidevZero** [comment]
Fixed in [2.11.2](https://github.com/omnidevZero/YouTubeRedux/commit/cb5fe0c1339580635b01630a1c6f53d9fde55ea2) which should be available soon.
