### ISSUE TITLE
[Feature Request] Default Quality Setting

### ISSUE THREAD

**Issue by LOuroboros** [omnidevZero/YouTubeRedux#30]
Hello. I just started to try out this addon, and I'm quite pleased so far.

Say, would it be possible to add an option in it to enforce a default quality for Youtube videos that is not automatic, and if it's not available use the next best option?

**Comment by omnidevZero** [comment]
The extension doesn't really focus on being a comprehensive tool that enhances YT functionality. Its main focus is visual changes. I'm sure there are other extensions or userscripts that specifically target this feature request so you might want to look around for these.

**Comment by LOuroboros** [comment]
> The extension doesn't really focus on being a comprehensive tool that enhances YT functionality. Its main focus is visual changes. I'm sure there are other extensions or userscripts that specifically target this feature request so you might want to look around for these.

I already did, and the only one that has worked does only work partially, as it can't set a default quality for Youtube videos embedded on external pages.

I understand it's out of scope so I won't pry further, but it is a shame. Thanks for answering.
