### ISSUE TITLE
[Bug] "Show precise value for likes/dislikes" doesn't work

### ISSUE THREAD

**Issue by LOuroboros** [omnidevZero/YouTubeRedux#32]
I just noticed this and figured it'd be a good idea to report it.
 
![Idle_20220513_0728462](https://user-images.githubusercontent.com/4485172/168266102-b5d58ef8-1c9a-4f74-b865-4a44e7d4826a.png)

**Comment by KingGamingYT** [comment]
With the new layout YouTube's rolling out, it's broken tons of stuff with the interface. This'll likely be fixed eventually.

**Comment by TheBSODAndWSODFan** [comment]
To restore old youtube watch page layout, see #46
