### ISSUE TITLE
[Bug] Favicon is Broken

### ISSUE THREAD

**Issue by KingGamingYT** [omnidevZero/YouTubeRedux#33]
It's all in the title. Seems YouTube has broken the favicon too. No idea what might be causing this. Tested in both Chrome and Firefox (Waterfox)
![image](https://user-images.githubusercontent.com/45918062/168402820-74b76a97-9f8c-46ab-86ce-32764bef203d.png)

**Comment by omnidevZero** [comment]
Fixed in 2.12.3 upcoming release.

**Comment by KingGamingYT** [comment]
Closing because 2.12.3 has been released and the bug has indeed been fixed.

**Comment by KingGamingYT** [comment]
Reopening this because it seems to still be slightly broken:

After restarting or shutting down the computer or browser and then coming back, all existing youtube tab favicons will become the default chrome website favicon or the default youtube favicon.
![image](https://user-images.githubusercontent.com/45918062/171064325-b513d365-148d-4076-ae1b-b7de7abbb44f.png)

Tested on both Chrome and Firefox

**Comment by KingGamingYT** [comment]
Seems to be fixed.
