### ISSUE TITLE
Bug that's stuck on loading until I refresh

### ISSUE THREAD

**Issue by m3k1e** [omnidevZero/YouTubeRedux#38]
I was watching Gamer Meld vids but the site is stuck on loading until I hit refresh. It's still annoying that I don't want to press F5 multiple times.
![chrome_3eSMan7iRZ](https://user-images.githubusercontent.com/41316133/171971003-a9152e09-a5d8-41b2-969d-03e79e334f1d.png)

**Comment by omnidevZero** [comment]
If the issue still occurs then try clearing your browsers cache (for youtube only). If this doesn't help, check if there is any YouTube Redux setting that specifically causes this issue.
