### ISSUE TITLE
[bug] video page layout doesn't work properly on certain accounts

### ISSUE THREAD

**Issue by saiveeon** [omnidevZero/YouTubeRedux#39]
when the new video page layout update was rolled out and youtube redux was updated to support it, i immediately started encountering this issue and have never seen it fixed since.
the video page layout does not display properly for me, but only on my main account.

here's what it looks like on the account i normally use:
![Annotation 2022-07-15 083107](https://user-images.githubusercontent.com/96271382/179234048-b86376ba-7c6e-4766-929a-ccb8551cfd7c.png)
note, the "show more" button is still there, but funnily enough, it's invisible until i click on it.

i switch to my other account i have tied to the same email, and...
![Annotation 2022-07-15 083110](https://user-images.githubusercontent.com/96271382/179234205-ad43cb16-17b4-41f6-938a-be9a6fd57334.png)
working entirely as it should!

i switch back to my main account, and the problem returns. though it seems that the show more button gets restored and now displays as "MORE..."
![Annotation 2022-07-15 083952](https://user-images.githubusercontent.com/96271382/179234720-c1a37379-64c1-4c90-ae48-6a965eaea303.png)

not to mention this quirk on my main account where every time i go to a new video page, the channel name/profile picture and subscriber button/count humorously starts to drift away from each other...
![Annotation 2022-07-15 083218](https://user-images.githubusercontent.com/96271382/179234645-ac8b63c5-bb21-40c3-8ce9-09de94653a8b.png)

i am using stock firefox, but i checked for the bug on microsoft edge (through the google chrome extension) and it happens on there as well. the bug happens on stock youtube redux settings too. i'm not sure if it's caused by a youtube setting on my main account. whatever that setting could be, i can't find it. if i happened to leave on some deprecated setting and it's somehow still active, well, that would suck.

**Comment by mrflamist** [comment]
I second this. For me, the layout is fine until I sign in. I too am using Firefox (well, Librewolf to be exact, but it's a fork of Firefox).
![layout-brokey](https://user-images.githubusercontent.com/88791223/179511920-409ff225-77b8-41a2-8769-4a2032ad823d.png)

**Comment by TheBSODAndWSODFan** [comment]
Use this tampermonkey script https://greasyfork.org/scripts/445015 it should work on main account @saiveeon
