### ISSUE TITLE
[ Feature Request ] Ability to work with Return Youtube Dislike

### ISSUE THREAD

**Issue by fbievan** [omnidevZero/YouTubeRedux#4]
Basically describes itself. Give the ability to work with Return Youtube Dislike. lol

**Comment by omnidevZero** [comment]
Will do.

**Comment by fbievan** [comment]
![image](https://user-images.githubusercontent.com/17110707/144537590-8b537a12-ac38-4f04-9815-2c8f9d948a90.png)
Theming on ratio does not work, but the dislike/like changes

**Comment by omnidevZero** [comment]
Added in 2.11.3.
