### ISSUE TITLE
add "by" text before author on video cards

### ISSUE THREAD

**Issue by TorutheRedFox** [omnidevZero/YouTubeRedux#41]
css needed:

```CSS
#text.ytd-channel-name {
    display: inline;
}
```
(also probably need font matching between the text)

html needed:
just add " by " (without quotation marks or any markup tags) before yt-formatted-string.ytd-channel-name in its parent div, like so
```HTML
<div id="container" class="style-scope ytd-channel-name">
  <div id="text-container" class="style-scope ytd-channel-name">
     by <yt-formatted-string id="text" title="" class="style-scope ytd-channel-name" ellipsis-truncate="">ChannelName</yt-formatted-string>
  </div>
  <tp-yt-paper-tooltip fit-to-visible-bounds="" class="style-scope ytd-channel-name" role="tooltip" tabindex="-1" style="inset: -28.4062px auto auto 156.547px;"><!--css-build:shady--><div id="tooltip" class="style-scope tp-yt-paper-tooltip hidden" style-target="tooltip">
  
    ChannelName
  
</div>
</tp-yt-paper-tooltip>
</div>
```

**Comment by TorutheRedFox** [comment]
or just do the html part with css ::before

**Comment by omnidevZero** [comment]
I want to avoid adding English string because people are using YouTube in many different languages and it would look jarring.

**Comment by TorutheRedFox** [comment]
maybe dynamically changing that string based on language?

**Comment by omnidevZero** [comment]
Well, considering YouTube currently supports over 80 languages I'd say it's not the best goal to have in mind! 😛

**Comment by TorutheRedFox** [comment]
maybe don't have it shown on languages that aren't supported and slowly add support for more over time?

this applies to other strings that Google removed or changed too by the way
