### ISSUE TITLE
This Tampermonkey Script Can Restore Youtube Watch Page

### ISSUE THREAD

**Issue by TheBSODAndWSODFan** [omnidevZero/YouTubeRedux#46]
This Tampermonkey Script https://greasyfork.org/scripts/445015 Can Restore Old Watch Page With Bold "DISLIKE" Text

Before (No 100% Volume Button)
![2022-08-03_21-07](https://user-images.githubusercontent.com/78845241/182630680-4be8d259-2b92-4db8-af0b-07407dae9b7a.png)
 
After
![2022-08-03_21-10](https://user-images.githubusercontent.com/78845241/182630820-e6d61737-64f8-411f-9717-8f9be6e7d103.png)

Can We Should Put This Script Or Feature Into YouTube Redux?

Browser: Brave Version 1.41.100 Chromium: 103.0.5060.134 (Official Build) Linux (64-bit) Profile 2
Extensions: YouTube Redux, And Tampermonkey

Im New On Github And Sorry For Bad English
Thanks :)

BTW 100% Volume Is The Feature To Disable Youtube Loudness Normalization Manually
Script https://gist.github.com/WouterG/acf1e901324aed77f466626fb5d6611f *This Script Doesnt Work On New Watch Page Layout.

**Comment by KingGamingYT** [comment]
This patch works on live streams but seems to not work on regular videos. It has a few visual errors.
![image](https://user-images.githubusercontent.com/45918062/182720278-eac8fbde-e3e7-4173-aa08-41ed4b18b960.png)
![image](https://user-images.githubusercontent.com/45918062/182720282-1718787c-27c8-49ae-a3b6-25c3d9f0138a.png)

**Comment by omnidevZero** [comment]
Thanks, I'll try to have it added in the next update. Initially I didn't want to hide the new layout and display the old hidden one as I feared that users would end up with the entire section missing in case YouTube decides to remove the old one permanently. However, it's been months and it's still there so I'll restore it via simply unhiding while I work properly restoring it within the new layout that will inevitably replace it.

**Comment by TorutheRedFox** [comment]
I mean it's still there because a lot of people, myself included, still don't have it

I don't imagine it'll be around for very long once it gets rolled out to everyone
