### ISSUE TITLE
Dislikes not displaying when in "alternative video page layout"

### ISSUE THREAD

**Issue by Lawyerlarge** [omnidevZero/YouTubeRedux#48]
![Screenshot 2022-08-03 11 00 57 PM](https://user-images.githubusercontent.com/110581315/182754562-933af373-86db-478f-9d55-ecd311123107.png)
Last time i tested this option in firefox, it had the same issue.

**Comment by omnidevZero** [comment]
Won't be fixed for now. There is a conflict with Return YouTube dislike which stops working when dislike button is moved to the left side. Even if I skipped moving it there are also other issues like properly updating dislikes count and having it work with precise values. Another thing is YouTube is no longer strings for "X dislikes" so I would have to strip "likes" as well to look consistent which would in turn make it look quite weird. So... it's a quite painful issue!
