### ISSUE TITLE
"not interested" text on premiere's like button?

### ISSUE THREAD

**Issue by TorutheRedFox** [omnidevZero/YouTubeRedux#52]
![image](https://user-images.githubusercontent.com/15708278/185612416-bcddeaa4-d5fb-4400-9bc4-272c8dfce039.png)

**Comment by KingGamingYT** [comment]
Random text appearing on the like and dislike counters with the new layout fix isn't awfully uncommon. (I've experienced it occasionally, I attached a picture I took a few weeks ago) I assume it's some formatting inconsistency and should be fixed when more patches for restoring the old layout on top of the new layout roll out.
![weird](https://user-images.githubusercontent.com/45918062/185627942-10ce709b-b051-4727-91ef-7cfc7198a28e.jpg)

**Comment by TorutheRedFox** [comment]
the thing is that this is still the old layout

**Comment by KingGamingYT** [comment]
Oh, well, probably just a bog standard bug that slipped through the cracks then.

**Comment by omnidevZero** [comment]
Have you guys got some example urls to follow in order to experience the issue?

**Comment by KingGamingYT** [comment]
It happens completely randomly for me, and I'm in the new layout, so I, unfortunately, have no links to share. Toru might though.

**Comment by TorutheRedFox** [comment]
it seems to affect live streams and premieres on my end
