### ISSUE TITLE
"Download" Button will not disappear if turned off

### ISSUE THREAD

**Issue by KingGamingYT** [omnidevZero/YouTubeRedux#53]
Minor issue regarding that the "Download" button under videos will not disappear even if it is turned off in Redux's settings.
![image](https://user-images.githubusercontent.com/45918062/185755479-d79b6bf8-8a55-4a44-b0b6-4fb1a152b4cd.png)

**Comment by omnidevZero** [comment]
Thanks, will be fixed in the next update!
