### ISSUE TITLE
Upload date not showing for recommended videos

### ISSUE THREAD

**Issue by cesar-0n** [omnidevZero/YouTubeRedux#55]
### **IMPORTANT, THIS ONLY HAPPENS IN THE RECOMMENDED VIDEOS ON THE PLAYER PAGE, IN A SEARCH AND ON THE MAIN PAGE IT APPEARS CORRECTLY**
WITH YOUTUBE REDUX
![Clipboarder 2022 08 25-004](https://user-images.githubusercontent.com/49728419/186646506-f6c9ca96-080f-469a-ab1d-6bb4357380d7.png)

WITHOUT YOUTUBE REDUX
![Clipboarder 2022 08 25-003](https://user-images.githubusercontent.com/49728419/186646714-1b67ce01-e5f4-49b5-813f-457d3d6f61cd.png)

Sorry that the examples are in Spanish

**Comment by TorutheRedFox** [comment]
youtube originally didn't show this, but making it an option would be nice

**Comment by omnidevZero** [comment]
> youtube originally didn't show this, but making it an option would be nice

This is also the reason why it's disabled by default in Redux. There is an option to restore it by unchecking hiding related videos age:
![image](https://user-images.githubusercontent.com/74119439/187036751-40dfdd12-49cb-428c-8182-ac26193db6b1.png)

**Comment by TorutheRedFox** [comment]
oh didn't notice it lol
