### ISSUE TITLE
Video playback bar broken when shuffling playlists

### ISSUE THREAD

**Issue by ghost** [omnidevZero/YouTubeRedux#56]
Every time I shuffle playlists, the video bar glitches out and the features on the right disappear, and the video slider also becomes longer.

**Comment by KingGamingYT** [comment]
Like this?
![image](https://user-images.githubusercontent.com/45918062/188234214-cc3ae726-2e4a-4828-a127-5a6db52a5812.png)

**Comment by ArbestRi** [comment]
No, it happens when shuffling playlists some of the time. Also, some parts of the bar flickers and disappear.
