### ISSUE TITLE
Bug That I Found When I Open Youtube On Incognito

### ISSUE THREAD

**Issue by TheBSODAndWSODFan** [omnidevZero/YouTubeRedux#60]
The Button Is Not Good....
![2022-09-09_14-55_1](https://user-images.githubusercontent.com/78845241/189301787-a950bd05-d2c7-4361-946d-1ea9c30e0617.png)
What Happen With Dislike Button?
![2022-09-09_14-55_2](https://user-images.githubusercontent.com/78845241/189301802-0b1c39e6-3fcd-4fbb-8f35-60e032cdb397.png)
Can You Hide Description Button?
![2022-09-09_14-55_3](https://user-images.githubusercontent.com/78845241/189301816-23908ce0-58a2-43c7-b219-369fc1678168.png)

**Comment by KingGamingYT** [comment]
No way they are testing ANOTHER new layout with these pill shapes...

**Comment by TorutheRedFox** [comment]
> No way they are testing ANOTHER new layout with these pill shapes...

they are
my chemistry teacher has it on her account

**Comment by omnidevZero** [comment]
Pretty wild. Now, if you open any video in incognito mode you will end up with 1 out of 3 layouts which is a lottery. For now I'll mark it as waiting for full feature rollout as there are quite a lot of dependencies between video page's settings in Redux and actually having everything work correctly on yet another layout requires significant work and who knows, maybe they will end up scrapping it or changing it yet once more.

**Comment by KingGamingYT** [comment]
What a mess.

**Comment by KingGamingYT** [comment]
![image](https://user-images.githubusercontent.com/45918062/189512567-b3ad00b4-3272-4702-94ab-c87847f7301d.png)
Seems I'm being infected with it too, my search bar has changed but nothing else.
