### ISSUE TITLE
Layout is broken with latest beta YouTube layout

### ISSUE THREAD

**Issue by NextinMono** [omnidevZero/YouTubeRedux#69]
Seems like something in the new YouTube layout makes the extension freak out, here's a few pictures

![image](https://user-images.githubusercontent.com/38560522/193423015-e0eea468-f44c-4a41-a10e-3d5bea8d000d.png)
![image](https://user-images.githubusercontent.com/38560522/193423052-db7487c7-679f-4576-b42d-dc5829e54a1e.png)

**Comment by KingGamingYT** [comment]
I've been covering this in #64.
