### ISSUE TITLE
Return YouTube Dislike compatibility is broken

### ISSUE THREAD

**Issue by qfoxb** [omnidevZero/YouTubeRedux#73]
It's showing "DISABLED BY OWNER" on a video with likes and dislikes enabled

With Redux enabled: 
![image](https://gyazo.com/a1649c9f23a9c688a7cb0ba49c3eb3d1.gif)

With Redux disabled:
![image](https://user-images.githubusercontent.com/42038239/195418008-ad35584f-1362-42cd-a5de-e01ccc271dcf.png)

**Comment by KingGamingYT** [comment]
![image](https://user-images.githubusercontent.com/45918062/195468794-eb935ba4-2c67-49bc-8e0a-4098cf79ccfe.png)
seems to work fine for me

**Comment by qfoxb** [comment]
Yeah that's the exact issue I was having

**Comment by Franck-Nein** [comment]
It's been broken for about a month for me, if you have Stylus, this quick fix should work [quickYoutubeLikesFix.user.css](https://gist.githubusercontent.com/Franck-Nein/905d3da23702cf58f7752029b25861f6/raw/ef46fc1467c9be9c234ec0970ed79545bb5a9eef/quickYoutubeLikesFix.user.css) (Should probably be removed when an actual fix is provided)
The only thing it does is change 
`yt-formatted-string[is-empty]:not(.use-shadow){display: nonet}`
with 
`yt-formatted-string[is-empty]:not(.use-shadow){display: unset !important;}`

**Comment by qfoxb** [comment]
Totally works!

**Comment by TorutheRedFox** [comment]
it broke again, but harder

**Comment by KingGamingYT** [comment]
This seems to have been fixed.
