### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by lynrayy** [omnidevZero/YouTubeRedux#75]
I found the old screenshot of youtube (2018) and found out that video hashtags are grey, not blue:
![image](https://user-images.githubusercontent.com/59417884/196067000-19ba53ad-3f93-4a3a-bdc6-77c0154bee37.png)

There are modern hashtags with YT Redux:
![image](https://user-images.githubusercontent.com/59417884/196067038-e2377f6c-74f1-4287-a491-7e5a2d7d44c0.png)

Please make it gray for more parity

**Comment by omnidevZero** [comment]
A month has passed but it's going to be implemented in the upcoming update. Thanks for the suggestion, nice catch!

**Comment by omnidevZero** [comment]
Closing as it was implemented a while ago.
