### ISSUE TITLE
Old icons + New icons for likes/dislikes off creates issues in comments

### ISSUE THREAD

**Issue by RYRY1002** [omnidevZero/YouTubeRedux#78]
![Example of problem](https://cdn.discordapp.com/attachments/814066163075252230/1038007964663029771/unknown.png)

**Comment by omnidevZero** [comment]
Not sure why the order of buttons is messed up here but their appearance will be fixed in the upcoming update.

**Comment by omnidevZero** [comment]
Closing as it was fixed a while ago. If the issue still occurs feel free to reopen the issue.
