### ISSUE TITLE
[Feature Improvement] Option to remove "cinematic" glow around video player in newest layout change

### ISSUE THREAD

**Issue by okh-mzny** [omnidevZero/YouTubeRedux#80]
The newest layout change to YouTube has added a dynamically updating "background glow" effect to the video player, especially observable in videos with very strong contrasts or colors:

![vivaldi_CESPJ9gqVW](https://user-images.githubusercontent.com/60819623/200127363-026e0799-8e56-4dfb-92fa-2fb686542ed6.png)

This effect uses a canvas element in a div with the `#cinematics` ID. A html canvas suggests a possible performance impact.

![vivaldi_aklF1tSghX](https://user-images.githubusercontent.com/60819623/200127436-394cd7af-2ec5-4753-8cca-5ca0f6bf6fe7.png)

I was able to block the `#cinematics` ID in uBlock, but I'm not sure whether this stops the canvas from being rendered at all. The cosmetic part certainly works:

![vivaldi_cVg5M0mGp3](https://user-images.githubusercontent.com/60819623/200127488-17817ddd-91f5-4bb5-a7f1-b89aee215d58.png)

I have heard from a friend who's wearing glasses that this effect reminds him of his glasses fogging up and he asked me to find a way to get rid of it 😅 

Would be cool if this cosmetic change option finds its way into YouTubeRedux.

Cheers!

**Comment by KingGamingYT** [comment]
Disable redux and any other page alterations, then flip the "Ambient Mode" switch in the youtube player settings.

**Comment by okh-mzny** [comment]
🤦  That flew right over my head, but to be fair after all the layout changes its hard to expect a feature to be toggleable within vanilla YouTube.

Thanks a lot for pointing this out! Closing now..
