### ISSUE TITLE
View counter on sidebar is missing

### ISSUE THREAD

**Issue by Snowy404** [omnidevZero/YouTubeRedux#81]
This happens with "Additional sidebar changes" On and Off

![03a8d9750f15c8024401779607439890](https://user-images.githubusercontent.com/65083757/200135007-8e1a719b-29ab-488c-b0c1-e406c06fae9a.png)

**Comment by omnidevZero** [comment]
Will be fixed in the next update, thanks!

**Comment by Snowy404** [comment]
> Will be fixed in the next update, thanks!

Still doesn't show the view count for me
![31f64d0d67117b206f422b3bc631063e](https://user-images.githubusercontent.com/65083757/200632151-a02dbcd3-aca1-455f-8e0d-17deba8e8eb6.png)

**Comment by omnidevZero** [comment]
Closing as it was fixed a while ago. If the issue still occurs feel free to reopen the issue.
