### ISSUE TITLE
Channel video page has too few videos per row.

### ISSUE THREAD

**Issue by Expletive** [omnidevZero/YouTubeRedux#82]
See the image. When you go to a channel and look at their videos page, only two videos are in each row. This happens for me with default settings on version 2.13.5.

There's an identical problem on the Live page.

![image](https://user-images.githubusercontent.com/9963278/200143470-b1bc20b0-b798-40f6-95f1-0969299e5924.png)

**Comment by KingGamingYT** [comment]
This is a known issue, however the amount of videos per row seems to vary per person.

**Comment by omnidevZero** [comment]
Will be fixed in the next update which will cause it to display 4 videos per row. I'll add an option to modify that number in the future.
