### ISSUE TITLE
Q: The YouTube Redux extension has been abandoned? A: Nope!

### ISSUE THREAD

**Issue by LautaroL20** [omnidevZero/YouTubeRedux#83]
The YT Redux extension has finally died? Everything would seem to indicate that the creator of it (@omnidevZero) seems to have taken the decision to definitively abandon this extension, because he no longer replies to any reviews from the Redux´s Chrome extension page, Reddit as well as neither in Github... 

It is a shame because this extension currently have +20.000 users that actually are using it according to the Chrome extensions page =(

Well, it was good while it lasted... 

**The only solution for this would be to install a similar extension which practically does the same who did YT Redux:** [7ktTube - 2016 REDUX](https://7kt.se/downloads/5/7kttube-2016-redux)

**Comment by KingGamingYT** [comment]
He has most certainly not abandoned the project. Just a few days ago Omnidev pushed out the first in a series of updates to fix youtube's layout changes and everything about those changes and progress related to reverting them has been thoroughly documented in my post #64.

**Comment by TorutheRedFox** [comment]
yt redux is under a major restructure to make it work right with the redesign
