### ISSUE TITLE
Scaling Issue with Videos Tab

### ISSUE THREAD

**Issue by KingGamingYT** [omnidevZero/YouTubeRedux#84]
I know the update literally just released however with the videos page fix thumbnail scaling has kinda been scuffed up, it should be 5 per row by default if I remember correctly.
![image](https://user-images.githubusercontent.com/45918062/200485084-b880ea98-75d6-4afd-8cfa-bfc1e0867753.png)

**Comment by omnidevZero** [comment]
This is correct behavior. YouTube displays 4 per row by default and the issue was that Redux's homepage number of videos per row setting was affecting other places like that channel page.
