### ISSUE TITLE
Dislikes aren't showing for me

### ISSUE THREAD

**Issue by gameshowrecaps** [omnidevZero/YouTubeRedux#85]
The bug started this morning.
![Screenshot 2022-11-08 120600](https://user-images.githubusercontent.com/57842610/200641857-3a00efd2-d530-4afc-b416-0834eb25ece7.png)

**Comment by omnidevZero** [comment]
This may be an issue with Return Youtube Dislike itself. Check with Redux disabled to confirm.

**Comment by gameshowrecaps** [comment]
It is indeed an issue with Return YouTube Dislike. People are reporting problems on the reviews on Firefox and Chrome. Turns out it's some infrastructure updates in progress.
