### ISSUE TITLE
[Firefox issue] When I open a video or any section of YT in another tab, the following elements will have the new "bigger appearance"

### ISSUE THREAD

**Issue by LautaroL20** [omnidevZero/YouTubeRedux#88]
This issue only affects the Firefox version of YT Redux. If I want to open a video in another tab, the following elements from the video page, which are marked in red on the screenshot from below, will look bigger (top bar, video bar and the word "show more"). Currently, the only way to fix this issue is by refreshing the page.

EDIT: This also happens with any section from YT that gets open in another tab.

![Screenshot](https://user-images.githubusercontent.com/12244376/200919555-090c1b44-6998-4784-b9ca-e7a5e66a9b66.png)

**Comment by KingGamingYT** [comment]
I am unable to replicate this issue, and on firefox I seem to have my own weird formatting issues.
![image](https://user-images.githubusercontent.com/45918062/201165273-baaafbf0-f629-488d-a983-942fc4bd3bf0.png)

**Comment by LautaroL20** [comment]
I can provide a video showing how to replicate this issue if needed. BTW, this issue have persisted into 2.13.7.

**Comment by omnidevZero** [comment]
Yeah I didn't make any changes to fix this issue yet. However, I was able to reproduce it just fine (as mentioned in the first post the trick is to open the video in a new tab) so I'll try to have it fixed in the next update.

**Comment by LautaroL20** [comment]
Testing this bug deeper, I have discovered that this issue will also happen in any YT section that gets open in another tab. Here is a screenshot showing a YT Channel that has been opened in another tab, but like I said, it also happens with other sections like subscription, library, history, etc:
![REDUX ISSUE](https://user-images.githubusercontent.com/12244376/202837459-9eee8785-a3b8-48fc-b3cc-8882fdd7a126.png)

**Comment by omnidevZero** [comment]
Fix incoming!

**Comment by LautaroL20** [comment]
I can confirm that this issue no longer happens in the last update.
