### ISSUE TITLE
User channel page only shows 4 video columns instead of 6.

### ISSUE THREAD

**Issue by LautaroL20** [omnidevZero/YouTubeRedux#89]
Two screenshots showing how they look now and how they looked.

![YT User channel page videos now](https://user-images.githubusercontent.com/12244376/200922249-a9842833-3e66-4c98-badf-08d2f247fdf8.png)

![YT User channel page videos then](https://user-images.githubusercontent.com/12244376/200923235-22aa93ea-e3c3-49d9-a365-0d7495934ff5.png)

**Comment by KingGamingYT** [comment]
See #84.

**Comment by LautaroL20** [comment]
This issue have persisted into 2.13.7.

**Comment by omnidevZero** [comment]
Not exactly an issue. See #84 as mentioned above and also #102 which I just created to keep track of it in the future.
