### ISSUE TITLE
The subscribe button of the video page as well as the profile pict next to it have visual issues

### ISSUE THREAD

**Issue by LautaroL20** [omnidevZero/YouTubeRedux#90]
Subscribe button looks wrong and is a bit misplaced, and the profile pict next to it now looks a bit smaller. Screenshots:

![Subscribe button is a bit misplaced and looks wrong](https://user-images.githubusercontent.com/12244376/200925125-fd2a580c-fdc8-495a-ba84-c0d63c485256.png)

![Subscribe button is a bit misplaced and looks wrong  2](https://user-images.githubusercontent.com/12244376/200925177-aa5699e1-94c3-4fdd-890d-d4318205edfc.png)

**Comment by omnidevZero** [comment]
😞 
Thanks for letting me know. Unfortunately I wasn't able to reproduce these issues. Does it only happen in dark theme? Are all videos affected?

**Comment by KingGamingYT** [comment]
> 😞 Thanks for letting me know. Unfortunately I wasn't able to reproduce these issues. Does it only happen in dark theme? Are all videos affected?

![image](https://user-images.githubusercontent.com/45918062/202266635-a6a6872a-e93f-4127-b255-3460339e4dcb.png)
It does indeed happen on light theme as well. I know it isn't a device issue as it happens on both my laptop (pictured here) and my home desktop. Perhaps it's a browser issue? I haven't seen any video where this doesn't happen.

**Comment by omnidevZero** [comment]
Ok I got an idea why it might happen but no clue why it actually does happen so let's do some group debugging! 
Could you please press Ctrl+Shift+C (this will open inspect element menu) and then click on the Subscribe button in its subscribed state (so with it having the bugged red background) and paste a snippet of the html that's displayed there? Like this:
![image](https://user-images.githubusercontent.com/74119439/202269782-bc4a514f-c0d5-454f-93f5-a23bb043e9aa.png)

**Comment by KingGamingYT** [comment]
> Ok I got an idea why it might happen but no clue why it actually does happen so let's do some group debugging! Could you please press Ctrl+Shift+C (this will open inspect element menu) and then click on the Subscribe button in its subscribed state (so with it having the bugged red background) and paste a snippet of the html that's displayed there?

"<div class="yt-spec-touch-feedback-shape__fill" style=""></div>"
Looks the same as yours, maybe I'm selecting the wrong css element?

**Comment by KingGamingYT** [comment]
![image](https://user-images.githubusercontent.com/45918062/202293094-f84792f9-2df4-4c65-b568-be446ff68da2.png)
what did i do to you github

**Comment by omnidevZero** [comment]
I need to see the bigger scope, the elements hierarchy starting from the <button> element should be enough. Next screenshot please!

**Comment by KingGamingYT** [comment]
> I need to see the bigger scope, the elements hierarchy starting from the element should be enough. Next screenshot please!

![image](https://user-images.githubusercontent.com/45918062/202294122-43b65a60-6386-4121-9dde-10af990457c8.png)

**Comment by omnidevZero** [comment]
Perfect, thanks, I'll look into it!

**Comment by LautaroL20** [comment]
> KingGamingYT said: "The subscribe button and its issues have persisted into 2.13.7."

I confirm that this issue still happens for me too.

**Comment by KingGamingYT** [comment]
While the recent fix pretty much patched it up, theres still a fairly minor visual difference in the color of text, this difference can be seen on other page elements too like the like and dislike numbers.

Old:
![image](https://user-images.githubusercontent.com/45918062/204073699-1207d564-885c-43b7-bad8-0bf8098a652c.png)

New:
![image](https://user-images.githubusercontent.com/45918062/204073702-3d0ba3dd-44a4-4c55-ac25-970f80ee698f.png)
