### ISSUE TITLE
The buttons "save", "cut", "thanks" and "share" words now looks bigger and their icons are enlightened for no reason.

### ISSUE THREAD

**Issue by LautaroL20** [omnidevZero/YouTubeRedux#92]
![Buttons now and then](https://user-images.githubusercontent.com/12244376/200927320-2f024dba-89a3-4b39-83fe-86d62fdada29.png)

**Comment by KingGamingYT** [comment]
I believe this is a known issue. Currently, External CSS scripts can be applied to fix this for the time being.

**Comment by omnidevZero** [comment]
Will be fixed soon!

**Comment by omnidevZero** [comment]
Closing as it was fixed a while ago. If the issue still occurs feel free to reopen the issue.
