### ISSUE TITLE
The "three dots" symbol button used to report a video or transcript it, is now in a different wrong place.

### ISSUE THREAD

**Issue by LautaroL20** [omnidevZero/YouTubeRedux#93]
![Three dots symbol](https://user-images.githubusercontent.com/12244376/200928541-e9f3b484-7306-4732-b809-455bcb7139fb.png)

**Comment by KingGamingYT** [comment]
1. This is a known issue, I don't think anyone has found out how to fix it yet.

2. Personal question, how'd you get extended subscriber counts?

**Comment by LautaroL20** [comment]
> KingGamingYT said: "Personal question, how'd you get extended subscriber counts?"

That is because I have the option "trim subscribers count" disabled.

**Comment by KingGamingYT** [comment]
> That is because I have the option "trim subscribers count" disabled.

Odd, I have it disabled as well however the shortened subscriber count is not altered.

**Comment by TorutheRedFox** [comment]
it's not like that for me, odd

**Comment by TorutheRedFox** [comment]
but then again i'm using a mountain of userscripts and custom css to fix things so...

**Comment by TorutheRedFox** [comment]
i think i have redone the styling there to reorder and realign the elements at some point using flex styling

**Comment by omnidevZero** [comment]
Closing as it was fixed a while ago. If the issue still occurs feel free to reopen the issue.
