### ISSUE TITLE
Incorrect Formatting On Videos Tab

### ISSUE THREAD

**Issue by KingGamingYT** [omnidevZero/YouTubeRedux#95]
This is a rare use case, but channels that have less than 4 videos have the row center aligned instead of left aligned. Is this intended behavior?
![image](https://user-images.githubusercontent.com/45918062/201003123-b4cda6a4-a8a9-47bb-8e45-479ea65a5f77.png)

**Comment by omnidevZero** [comment]
Kinda intended but not really 😄. Fixed for the next update!
