### ISSUE TITLE
When searching for a channel name on YouTube, I cannot click on it

### ISSUE THREAD

**Issue by gameshowrecaps** [omnidevZero/YouTubeRedux#96]
![Screenshot(4)](https://user-images.githubusercontent.com/57842610/201270849-0fd217b7-d939-4171-852c-a152bc0daed6.png)

Can only click when it's underneath a video title.

**Comment by omnidevZero** [comment]
I'm not able to reproduce this issue. Does it still occur?

**Comment by gameshowrecaps** [comment]
Apparently it fixed itself.
