### ISSUE TITLE
Another formatting issue imposed by YouTube

### ISSUE THREAD

**Issue by KingGamingYT** [omnidevZero/YouTubeRedux#97]
![image](https://user-images.githubusercontent.com/45918062/201535466-7ada6fc8-d6eb-4b0a-ad63-4a1fa9a34342.png)
Refer to ParashockX comic #352 for more information.
(They made it all left aligned. It should be center aligned.)

**Comment by omnidevZero** [comment]
Fix merged (#99). Coming in the next update.
