### ISSUE TITLE
Videos Sidebar has no dates. 

### ISSUE THREAD

**Issue by TheMom1235** [omnidevZero/YouTubeRedux#98]
Unless I'm missing a setting, there aren't any "uploaded 6 months ago" on the sidebar. 
![763587649675873](https://user-images.githubusercontent.com/118135214/201543579-c21a7014-54b4-4a67-89d1-357fd827286c.png)

**Comment by omnidevZero** [comment]
![image](https://user-images.githubusercontent.com/74119439/201551614-8b18143d-e08d-4d98-98bd-3bb142191c32.png)
Uncheck this one. It's enabled by default to be consistent with old layout.
